[package]
name = "erica-watch"
version = "0.1.0"
edition = "2021"

[dependencies]
leptess = "0.14.0"
pdf-extract = "0.6.4"
regex = "1.8.1"
reqwest = { version = "0.11.16", features = ["blocking"] }
screenshots = "0.5.2"
select = "0.6.0"
tokio = { version = "1.25.0", features = ["full"] }
